### ISSUE TITLE
K-Bots Lack Animations

### ISSUE THREAD

**Issue by misterperson** [Dragun123/SCTA#173]
I have not tested every unit, but ARM T1 Con bots, FARKs, and Pelicans lack some/all animations.

**Comment by Dragun123** [comment]
this is correct, that one of the things that need to be done. Only units with animation, walking ones anyways are the commanders (and decoms), CORAK, and Drake.

**Comment by misterperson** [comment]
This is NoHome on the Discord

**Comment by Axle1975** [comment]
(/) units/ARMACK/ARMACK_unit.bp
( ) units/ARMAMPH/ARMAMPH_unit.bp
( ) units/ARMASER/ARMASER_unit.bp
( ) units/ARMCK/ARMCK_unit.bp
( ) units/ARMDECOM/ARMDECOM_unit.bp
( ) units/ARMFARK/ARMFARK_unit.bp
( ) units/ARMFAST/ARMFAST_unit.bp
( ) units/ARMFIDO/ARMFIDO_unit.bp
( ) units/ARMFLEA/ARMFLEA_unit.bp
( ) units/ARMHAM/ARMHAM_unit.bp
( ) units/ARMJETH/ARMJETH_unit.bp
( ) units/ARMMAV/ARMMAV_unit.bp
( ) units/ARMPW/ARMPW_unit.bp
( ) units/ARMROCK/ARMROCK_unit.bp
( ) units/ARMSNIPE/ARMSNIPE_unit.bp
( ) units/ARMVADER/ARMVADER_unit.bp
( ) units/ARMWAR/ARMWAR_unit.bp
( ) units/ARMZEUS/ARMZEUS_unit.bp

( ) units/CORACK/CORACK_unit.bp
( ) units/CORAK/CORAK_unit.bp
( ) units/CORAMPH/CORAMPH_unit.bp
( ) units/CORCAN/CORCAN_unit.bp
( ) units/CORCK/CORCK_unit.bp
( ) units/CORCRASH/CORCRASH_unit.bp
( ) units/CORDECOM/CORDECOM_unit.bp
( ) units/CORFAST/CORFAST_unit.bp
( ) units/CORKROG/CORKROG_unit.bp
( ) units/CORMORT/CORMORT_unit.bp
( ) units/CORNECRO/CORNECRO_unit.bp
( ) units/CORPYRO/CORPYRO_unit.bp
( ) units/CORROACH/CORROACH_unit.bp
( ) units/CORSPEC/CORSPEC_unit.bp
( ) units/CORSTORM/CORSTORM_unit.bp
